project:
  type: website
  output-dir: docs

website:
  title: "Evi Papadaki"
  favicon: logo.png
  navbar:
    right:
      - href: index.qmd
        text: Home
     # - href: aboutme.qmd
     #   text: About me
      - bibliography.qmd
      - href: resume.pdf
        text: CV
        target: _blank
      - text: get in touch!
        menu:
         - icon: instagram
           text: instagram
           href: https://www.instagram.com/academic_scribbles/
           target: _blank
         - icon: linkedin
           text: linkedin
           href: https://www.linkedin.com/in/evi-papadaki/
           target: _blank
         - icon: envelope
           text: email
           href: mailto:pp949@bath.ac.uk
  page-footer: 
      background: white
      left: Copyright 2024, Evi Papadaki
    
format:
  html:
    theme: 
     - styles.css
    mainfont: Nunito
    toc: true
    toc-depth: 2

editor: visual

