project:
  type: website
  output-dir: docs

website:
  title: "Academic Scribbles"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - aboutme.qmd
      - bibliography.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    toc-depth: 2

editor: visual

